name=Billy
version=1.4.8
author=Dmitriy Efimov aka Erling Sigurdson <efimov-d-v@yandex.ru>
maintainer=Dmitriy Efimov aka Erling Sigurdson <efimov-d-v@yandex.ru>
sentence=Control various devices using UART and wireless protocols.
paragraph=Control various devices using UART and wireless protocols.
category=Device Control
url=https://github.com/ErlingSigurdson/Billy
architectures=*
